"""libxr parse 的 STM32 解析器（libxr.peripheral_analyzer_stm32）：输出位置、生成说明和读出的
外设配置。
The STM32 parser of libxr parse (libxr.peripheral_analyzer_stm32): where its YAML goes, the
notice at its top, and the peripheral configuration it reads.
"""

import tempfile
import unittest
from pathlib import Path

import reference_projects
from fixtures import IOC, TestCase, run_libxr

from libxr import peripheral_analyzer_stm32

NOTICE = "# Generated by `libxr parse` from the CubeMX .ioc file; do not edit by hand."


class ParseIoc(TestCase):
    """命令行：读取目录中唯一的 .ioc 文件并写出 YAML。
    The command line: read the one .ioc file of a directory and write the YAML.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.project = Path(temporary.name)
        (self.project / "demo.ioc").write_text(IOC, encoding="utf-8")

    def parse(self, *argv):
        """以这些参数运行 libxr parse，返回退出码。
        Run libxr parse with these arguments and return the exit code.
        """
        return run_libxr("parse", "-d", str(self.project), *argv)[0]

    def test_the_default_output_is_config_yaml_in_the_directory(self):
        self.assertEqual(self.parse(), 0)
        output = self.project / ".config.yaml"
        self.assertEqual(output.read_text(encoding="utf-8").splitlines()[0], NOTICE)
        self.assertFalse((self.project / "demo.yaml").exists())

    def test_an_explicit_output_is_kept(self):
        self.assertEqual(self.parse("-o", str(self.project / "cubemx.yaml")), 0)
        self.assertTrue((self.project / "cubemx.yaml").is_file())
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_several_ioc_files_are_refused(self):
        (self.project / "other.ioc").write_text(IOC, encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertIn("holds several .ioc files (demo.ioc, other.ioc)", logs.output[0])
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_an_unreadable_ioc_file_fails_the_command(self):
        (self.project / "demo.ioc").write_bytes(b"Mcu.Family=\xff\xfe\n")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertTrue(logs.output[0].startswith("ERROR:root:File processing failed: "))
        self.assertFalse((self.project / ".config.yaml").exists())


class ReferenceProjects(TestCase):
    """两个真实 BSP 工程的解析结果与基准文件逐字节相同。
    The parse of two real BSP projects equals the reference files byte for byte.
    """

    def test_the_parsed_configuration_is_the_reference(self):
        for name in reference_projects.PROJECTS:
            with self.subTest(project=name), tempfile.TemporaryDirectory() as temporary:
                output = reference_projects.parse(name, Path(temporary))
                expected = reference_projects.DATA / name / "expected" / "cubemx.yaml"
                self.assertEqual(output.read_bytes(), expected.read_bytes())


class ParsedConfiguration(TestCase):
    """从 .ioc 条目读出的外设和 RTOS 配置。
    The peripheral and RTOS configuration read from .ioc entries.
    """

    def parse(self, extra):
        """解析 IOC 加上 extra 条目后的配置。
        Parse IOC with the extra entries appended.
        """
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "demo.ioc"
            path.write_text(IOC + extra, encoding="utf-8")
            return peripheral_analyzer_stm32.parse_ioc_file(str(path))

    def test_freertos_tasks_heap_and_features(self):
        # CubeMX 用分号分隔多个任务，功能开关写 1 或 0。
        # CubeMX separates tasks with semicolons and writes feature flags as 1 or 0.
        freertos = self.parse(
            "FREERTOS.Tasks01=defaultTask,0,3192,StartDefaultTask,Default,NULL,Dynamic,NULL,NULL;"
            "worker,24,256,StartWorker,Default,NULL,Dynamic,NULL,NULL\n"
            "FREERTOS.configTOTAL_HEAP_SIZE=65536\n"
            "FREERTOS.INCLUDE_vTaskDelayUntil=1\n"
            "FREERTOS.INCLUDE_vTaskDelete=0\n"
        )["FreeRTOS"]
        self.assertTrue(freertos["Enabled"])
        self.assertEqual(
            freertos["Tasks"],
            {
                "defaultTask": {
                    "Priority": "0",
                    "StackSize": "3192B",
                    "EntryFunction": "StartDefaultTask",
                    "Type": "Default",
                },
                "worker": {
                    "Priority": "24",
                    "StackSize": "256B",
                    "EntryFunction": "StartWorker",
                    "Type": "Default",
                },
            },
        )
        self.assertEqual((freertos["Heap"], freertos["Features"]), ("65536B", ["vTaskDelayUntil"]))

    def test_can_flags_follow_their_hal_meaning(self):
        # ABOM 是自动离线恢复，NART 是禁止自动重传；未写出的参数取 HAL 的默认值。
        # ABOM is automatic bus-off management and NART disables automatic retransmission;
        # parameters CubeMX omits keep the HAL defaults.
        can = self.parse("CAN1.ABOM=ENABLE\nCAN1.NART=ENABLE\nCAN1.AWUM=ENABLE\n")["Peripherals"][
            "CAN"
        ]
        flags = ("AutoBusOff", "AutoRetransmission", "AutoWakeup")
        self.assertEqual([can["CAN1"][f] for f in flags], [True, False, True])
        self.assertEqual([can["CAN2"][f] for f in flags], [False, True, False])

    def test_dma_requests_add_no_empty_peripheral_groups(self):
        peripherals = self.parse("")["Peripherals"]
        self.assertEqual(peripherals["USART"]["USART1"]["DMA_RX"], "ENABLE")
        self.assertNotIn("ADC", peripherals)
        self.assertNotIn("I2C", peripherals)


class Timebase(TestCase):
    """HAL 时基应是中断优先级最高的普通定时器，否则警告。
    The HAL timebase should be a general-purpose timer with the highest interrupt priority;
    anything else is warned about.
    """

    TIMER = "NVIC.TimeBase=TIM6_DAC_IRQn\nNVIC.TimeBaseIP=TIM6\n"
    parse = ParsedConfiguration.parse

    def test_systick_is_warned_about(self):
        with self.assertLogs(level="WARNING") as logs:
            self.assertEqual(self.parse("")["Timebase"], {"Source": "SysTick", "IRQ": None})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase is SysTick. In STM32CubeMX, set SYS > Timebase "
                "Source to a general-purpose timer (such as TIM6) and give its interrupt the "
                "highest preemption priority (0) in NVIC."
            ],
        )

    def test_a_timer_needs_the_highest_priority(self):
        with self.assertLogs(level="WARNING") as logs:
            timebase = self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:5\\:0\\:false\\:true\n")
        self.assertEqual(timebase["Timebase"], {"Source": "TIM6", "IRQ": "TIM6_DAC_IRQn"})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase interrupt TIM6_DAC_IRQn (TIM6) has preemption "
                "priority 5. In STM32CubeMX, set it to the highest (0) in NVIC."
            ],
        )
        with self.assertNoLogs(level="WARNING"):
            self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:0\\:0\\:false\\:true\n")


if __name__ == "__main__":
    unittest.main()
