"""xr_parse_ioc 的输出位置与生成说明。
Where xr_parse_ioc writes its YAML, and the notice at its top.
"""

import contextlib
import io
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from test_determinism import IOC

from libxr import peripheral_analyzer_stm32

NOTICE = "# Generated by xr_parse_ioc from the CubeMX .ioc file; do not edit by hand."


class ParseIoc(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.project = Path(temporary.name)
        (self.project / "demo.ioc").write_text(IOC, encoding="utf-8")

    def parse(self, *argv):
        with (
            patch.object(sys, "argv", ["xr_parse_ioc", "-d", str(self.project), *argv]),
            contextlib.redirect_stdout(io.StringIO()),
        ):
            try:
                peripheral_analyzer_stm32.main()
            except SystemExit as exit:
                return exit.code
        return 0

    def test_the_default_output_is_config_yaml_in_the_directory(self):
        self.assertEqual(self.parse(), 0)
        output = self.project / ".config.yaml"
        self.assertEqual(output.read_text(encoding="utf-8").splitlines()[0], NOTICE)
        self.assertFalse((self.project / "demo.yaml").exists())

    def test_an_explicit_output_is_kept(self):
        self.assertEqual(self.parse("-o", str(self.project / "cubemx.yaml")), 0)
        self.assertTrue((self.project / "cubemx.yaml").is_file())
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_several_ioc_files_are_refused(self):
        (self.project / "other.ioc").write_text(IOC, encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertIn("holds several .ioc files (demo.ioc, other.ioc)", logs.output[0])
        self.assertFalse((self.project / ".config.yaml").exists())


if __name__ == "__main__":
    unittest.main()
