"""libxr parse 的 STM32 解析器（libxr.peripheral_analyzer_stm32）：输出位置、生成说明和读出的
外设配置。
The STM32 parser of libxr parse (libxr.peripheral_analyzer_stm32): where its YAML goes, the
notice at its top, and the peripheral configuration it reads.
"""

import contextlib
import io
import tempfile
import textwrap
import unittest
from pathlib import Path
from unittest import mock

from fixtures import IOC, GeneratorTestCase, TestCase, run_libxr

from libxr import peripheral_analyzer_stm32

NOTICE = "# Generated by `libxr parse` from the CubeMX .ioc file; do not edit by hand."

# STM32CubeH5 例程 UART_TwoBoards_ComDMA（STM32H503）的 .ioc 片段：USART1 的发送和接收各用
# 一个 GPDMA1 通道，另有一个启用的 IWDG。
# An .ioc excerpt of the STM32CubeH5 example UART_TwoBoards_ComDMA (STM32H503): USART1 sends
# and receives through one GPDMA1 channel each, plus an enabled IWDG.
H5_IOC = textwrap.dedent("""\
    Mcu.Family=STM32H5
    Mcu.Name=STM32H503RBTx
    Mcu.UserName=STM32H503RBTx
    Mcu.CPN=STM32H503RBT6
    Mcu.IP0=GPDMA1
    Mcu.IP1=IWDG
    Mcu.IP2=USART1
    Mcu.IPNb=3
    GPDMA1.DIRECTION_GPDMACH0=DMA_MEMORY_TO_PERIPH
    GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX
    GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX
    IWDG.Prescaler=IWDG_PRESCALER_64
    IWDG.Reload=4095
    PA1.Signal=USART1_RX
    PB14.Signal=USART1_TX
    USART1.BaudRate=9600
    USART1.IPParameters=BaudRate,VirtualMode
    USART1.VirtualMode=VM_ASYNC
    VP_IWDG_VS_IWDG.Mode=IWDG_Activate
    """)

# STM32CubeH5 例程 USART_SlaveMode_DMA 的片段：USART1 为同步从机，CubeMX 生成的句柄是
# USART_HandleTypeDef husart1。
# An excerpt of the STM32CubeH5 example USART_SlaveMode_DMA: USART1 is a synchronous slave and
# the handle CubeMX generates is USART_HandleTypeDef husart1.
SYNC_USART_IOC = textwrap.dedent(r"""
    Mcu.Family=STM32H5
    Mcu.CPN=STM32H503RBT6
    GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX
    GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX
    PB12.Mode=Synchronous Slave
    PB12.Signal=USART1_CK
    PB14.Mode=Synchronous Slave
    PB14.Signal=USART1_TX
    PB15.Mode=Synchronous Slave
    PB15.Signal=USART1_RX
    USART1.BaudRate=9600
    USART1.VirtualMode=VM_SYNC
    USART1.VirtualMode-Synchronous\ Slave=VM_SYNC
    """)

# STM32CubeH5 例程 SMBUS_TwoBoards_ComIT_Master 的片段：I2C2 为 SMBus，CubeMX 生成的句柄是
# SMBUS_HandleTypeDef hsmbus2。
# An excerpt of the STM32CubeH5 example SMBUS_TwoBoards_ComIT_Master: I2C2 runs SMBus and the
# handle CubeMX generates is SMBUS_HandleTypeDef hsmbus2.
SMBUS_IOC = textwrap.dedent("""
    Mcu.Family=STM32H5
    Mcu.CPN=STM32H503RBT6
    I2C2.SMBusPeripheralMode=SMBUS_PERIPHERAL_MODE_SMBUS_HOST
    I2C2.Timing=0x608087CA
    Mcu.IP1=I2C2
    PB10.Mode=SMBus-two-wire-Interface
    PB10.Signal=I2C2_SCL
    PB13.Mode=SMBus-two-wire-Interface
    PB13.Signal=I2C2_SDA
    """)

# STM32CubeMX 6.18.1 保存的 DevC 副本中 ADC3 的片段：12 个 rank，第 12 个再次转换 IN8。key 按
# 文本排序，Channel-10 和 Channel-11 在 Channel-2 之前；CubeMX 生成的 MX_ADC3_Init 按 rank
# 依次配置 IN8、1、2、3、5、6、7、9、13、14、15、8。
# ADC3 of a DevC copy saved by STM32CubeMX 6.18.1: 12 ranks, the 12th converting IN8 again.
# The keys are sorted as text, Channel-10 and Channel-11 before Channel-2; MX_ADC3_Init
# generated by CubeMX configures IN8, 1, 2, 3, 5, 6, 7, 9, 13, 14, 15, 8 by rank.
ADC_RANKS_IOC = textwrap.dedent(r"""
    ADC3.Channel-0\#ChannelRegularConversion=ADC_CHANNEL_8
    ADC3.Channel-1\#ChannelRegularConversion=ADC_CHANNEL_1
    ADC3.Channel-10\#ChannelRegularConversion=ADC_CHANNEL_15
    ADC3.Channel-11\#ChannelRegularConversion=ADC_CHANNEL_8
    ADC3.Channel-2\#ChannelRegularConversion=ADC_CHANNEL_2
    ADC3.Channel-3\#ChannelRegularConversion=ADC_CHANNEL_3
    ADC3.Channel-4\#ChannelRegularConversion=ADC_CHANNEL_5
    ADC3.Channel-5\#ChannelRegularConversion=ADC_CHANNEL_6
    ADC3.Channel-6\#ChannelRegularConversion=ADC_CHANNEL_7
    ADC3.Channel-7\#ChannelRegularConversion=ADC_CHANNEL_9
    ADC3.Channel-8\#ChannelRegularConversion=ADC_CHANNEL_13
    ADC3.Channel-9\#ChannelRegularConversion=ADC_CHANNEL_14
    ADC3.ContinuousConvMode=ENABLE
    ADC3.DMAContinuousRequests=ENABLE
    ADC3.NbrOfConversion=12
    ADC3.Rank-0\#ChannelRegularConversion=1
    ADC3.Rank-1\#ChannelRegularConversion=2
    ADC3.Rank-10\#ChannelRegularConversion=11
    ADC3.Rank-11\#ChannelRegularConversion=12
    ADC3.ScanConvMode=ENABLE
    Dma.ADC3.9.Instance=DMA2_Stream1
    Dma.ADC3.9.Mode=DMA_CIRCULAR
    Dma.Request9=ADC3
    Mcu.CPN=STM32F407IGH6
    Mcu.Family=STM32F4
    """)


class ParseIoc(TestCase):
    """命令行：读取目录中唯一的 .ioc 文件并写出 YAML。
    The command line: read the one .ioc file of a directory and write the YAML.
    """

    def setUp(self):
        super().setUp()
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.project = Path(temporary.name)
        (self.project / "demo.ioc").write_text(IOC, encoding="utf-8")

    def parse(self, *argv):
        """以这些参数运行 libxr parse，返回退出码。
        Run libxr parse with these arguments and return the exit code.
        """
        return run_libxr("parse", "-d", str(self.project), *argv)[0]

    def test_the_default_output_is_config_yaml_in_the_directory(self):
        self.assertEqual(self.parse(), 0)
        output = self.project / ".config.yaml"
        self.assertEqual(output.read_text(encoding="utf-8").splitlines()[0], NOTICE)
        self.assertFalse((self.project / "demo.yaml").exists())

    def test_the_output_directory_is_created_and_written_without_anchors(self):
        output = self.project / ".ci-tools" / "cubemx.yaml"
        self.assertEqual(self.parse("-o", str(output)), 0)
        text = output.read_text(encoding="utf-8")
        # USART1 的 DMA 配置同时出现在外设和 DMA 段中，两处都完整写出。
        # The DMA configuration of USART1 is under the peripheral and in the DMA section, both
        # written in full.
        self.assertNotIn("&id", text)
        self.assertEqual(text.count("stream: DMA2_Stream5"), 2)

    def test_an_explicit_output_is_kept(self):
        self.assertEqual(self.parse("-o", str(self.project / "cubemx.yaml")), 0)
        self.assertTrue((self.project / "cubemx.yaml").is_file())
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_several_ioc_files_are_refused(self):
        (self.project / "other.ioc").write_text(IOC, encoding="utf-8")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertIn("holds several .ioc files (demo.ioc, other.ioc)", logs.output[0])
        self.assertFalse((self.project / ".config.yaml").exists())

    def test_an_unreadable_ioc_file_fails_the_command(self):
        (self.project / "demo.ioc").write_bytes(b"Mcu.Family=\xff\xfe\n")
        with self.assertLogs(level="ERROR") as logs:
            self.assertEqual(self.parse(), 1)
        self.assertEqual(
            logs.output,
            [
                f"ERROR:root:{self.project / 'demo.ioc'} is not UTF-8 text (byte 12); "
                "save it as UTF-8"
            ],
        )
        self.assertFalse((self.project / ".config.yaml").exists())


class ParsedConfiguration(TestCase):
    """从 .ioc 条目读出的外设和 RTOS 配置。
    The peripheral and RTOS configuration read from .ioc entries.
    """

    def parse(self, extra, ioc=IOC):
        """解析 ioc 加上 extra 条目后的配置。
        Parse ioc with the extra entries appended.
        """
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "demo.ioc"
            path.write_text(ioc + extra, encoding="utf-8")
            return peripheral_analyzer_stm32.parse_ioc_file(str(path))

    def test_freertos_tasks_heap_and_features(self):
        # CubeMX 用分号分隔多个任务，功能开关写 1 或 0。
        # CubeMX separates tasks with semicolons and writes feature flags as 1 or 0.
        freertos = self.parse(
            "FREERTOS.Tasks01=defaultTask,0,3192,StartDefaultTask,Default,NULL,Dynamic,NULL,NULL;"
            "worker,24,256,StartWorker,Default,NULL,Dynamic,NULL,NULL\n"
            "FREERTOS.configTOTAL_HEAP_SIZE=65536\n"
            "FREERTOS.INCLUDE_vTaskDelayUntil=1\n"
            "FREERTOS.INCLUDE_vTaskDelete=0\n"
        )["FreeRTOS"]
        self.assertTrue(freertos["Enabled"])
        self.assertEqual(
            freertos["Tasks"],
            {
                "defaultTask": {
                    "Priority": "0",
                    "StackSize": "3192 words",
                    "EntryFunction": "StartDefaultTask",
                    "Type": "Default",
                },
                "worker": {
                    "Priority": "24",
                    "StackSize": "256 words",
                    "EntryFunction": "StartWorker",
                    "Type": "Default",
                },
            },
        )
        self.assertEqual((freertos["Heap"], freertos["Features"]), ("65536B", ["vTaskDelayUntil"]))

    def test_sizes_and_dma_priorities_keep_their_values(self):
        # CubeMX 可以把堆大小写成十六进制；DMA 优先级有 VERY_HIGH 一级。
        # CubeMX may write the heap size in hexadecimal; DMA priorities have a VERY_HIGH level.
        parsed = self.parse(
            "FREERTOS.configTOTAL_HEAP_SIZE=0x18800\n"
            "Dma.USART1_RX.0.Priority=DMA_PRIORITY_VERY_HIGH\n"
            "Dma.USART1_TX.1.Priority=DMA_PRIORITY_LOW\n"
        )
        self.assertEqual(parsed["FreeRTOS"]["Heap"], "100352B")
        self.assertNotIn("AllocationMethod", parsed["FreeRTOS"])
        configurations = parsed["DMA"]["Configurations"]
        self.assertEqual(configurations["USART1_RX_0"]["priority"], "VeryHigh")
        self.assertEqual(configurations["USART1_TX_1"]["priority"], "Low")

    def test_fmpi2c_is_not_taken_for_i2c(self):
        # LibXR 没有 FMPI2C 驱动；当成 I2C 会生成类型不符的 I2C_HandleTypeDef 句柄。
        # LibXR has no FMPI2C driver; taken for I2C it would get a mistyped I2C_HandleTypeDef.
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("PC6.Signal=FMPI2C1_SCL\nPC7.Signal=FMPI2C1_SDA\n")[
                "Peripherals"
            ]
        self.assertNotIn("I2C", peripherals)
        fmpi2c = [line for line in logs.output if "FMPI2C1" in line]
        self.assertEqual(
            fmpi2c, ["WARNING:root:FMPI2C1 is not generated: LibXR has no driver for it"]
        )

    def test_a_dac_entry_without_a_comma_is_skipped(self):
        with self.assertLogs(level="WARNING") as logs:
            parsed = self.parse("SH.COMP_DAC1_group.0=DAC_OUT1\n")
        self.assertIsNotNone(parsed)
        self.assertIn(
            "Ignored DAC entry without a channel and an alias: SH.COMP_DAC1_group.0=DAC_OUT1",
            "\n".join(logs.output),
        )

    def test_a_parse_error_logs_its_traceback_at_debug_level(self):
        with (
            mock.patch.object(
                peripheral_analyzer_stm32.TIMParser, "parse", side_effect=RuntimeError("boom")
            ),
            self.assertLogs(level="DEBUG") as logs,
        ):
            self.assertIsNone(self.parse(""))
        errors = [r for r in logs.records if r.levelname == "ERROR"]
        self.assertEqual([r.getMessage() for r in errors], ["Parsing failed: boom"])
        self.assertIsNotNone(logs.records[-1].exc_info)

    def test_can_flags_follow_their_hal_meaning(self):
        # ABOM 是自动离线恢复，NART 是禁止自动重传；未写出的参数取 HAL 的默认值。
        # ABOM is automatic bus-off management and NART disables automatic retransmission;
        # parameters CubeMX omits keep the HAL defaults.
        can = self.parse("CAN1.ABOM=ENABLE\nCAN1.NART=ENABLE\nCAN1.AWUM=ENABLE\n")["Peripherals"][
            "CAN"
        ]
        flags = ("AutoBusOff", "AutoRetransmission", "AutoWakeup")
        self.assertEqual([can["CAN1"][f] for f in flags], [True, False, True])
        self.assertEqual([can["CAN2"][f] for f in flags], [False, True, False])

    def test_dma_requests_add_no_empty_peripheral_groups(self):
        peripherals = self.parse("")["Peripherals"]
        self.assertEqual(peripherals["USART"]["USART1"]["DMA_RX"], "ENABLE")
        self.assertNotIn("ADC", peripherals)
        self.assertNotIn("I2C", peripherals)

    def test_watchdogs_are_listed_once_with_their_values(self):
        # 以前看门狗在外设列表和单独的看门狗段各出现一次，外设列表那一行没有数值。
        # Watchdogs used to appear in the peripheral list and again in a separate watchdog
        # section, the peripheral line without values.
        with self.assertLogs(level="WARNING"):
            parsed = self.parse("", H5_IOC)
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            peripheral_analyzer_stm32.print_summary(parsed)
        self.assertEqual(
            output.getvalue().split("Active Peripherals:\n")[1],
            "  USART: 1 instance(s)\n"
            "    USART1: BaudRate=9600\n"
            "  IWDG: 1 instance(s)\n"
            "    IWDG: Enabled=True | Prescaler=IWDG_PRESCALER_64 | Reload=4095\n",
        )


class ChannelDma(GeneratorTestCase):
    """GPDMA、HPDMA、LPDMA 的通道请求打开外设的 DMA，生成器据此分配缓冲区。
    Channel requests of GPDMA, HPDMA and LPDMA enable the DMA of a peripheral, and the
    generator allocates its buffers from that.
    """

    def parse(self, ioc):
        """解析 ioc 并返回配置；忽略 SysTick 时基的警告。
        Parse ioc and return the configuration; the SysTick timebase warning is ignored.
        """
        with self.assertLogs(level="WARNING") as self.logs:
            return ParsedConfiguration.parse(self, "", ioc)

    def test_gpdma_requests_give_uart_buffers(self):
        # 以前只读 Dma.RequestN，H5 的 USART1 生成为 STM32UART usart1(&huart1, {nullptr, 0},
        # {nullptr, 0}, 5)。
        # Only Dma.RequestN used to be read, and USART1 of the H5 became
        # STM32UART usart1(&huart1, {nullptr, 0}, {nullptr, 0}, 5).
        parsed = self.parse(H5_IOC)
        usart1 = parsed["Peripherals"]["USART"]["USART1"]
        self.assertEqual((usart1["DMA_TX"], usart1["DMA_RX"]), ("ENABLE", "ENABLE"))
        self.assertEqual(
            usart1["dma"]["dma_tx"],
            {
                "request_id": "GPDMACH0",
                "peripheral": "USART1_TX",
                "dma_type": "GPDMA",
                "stream": "GPDMA1_Channel0",
                "direction_full": "memory_to_periph",
            },
        )
        self.assertEqual(usart1["dma"]["dma_rx"]["stream"], "GPDMA1_Channel1")
        self.assertEqual(
            parsed["DMA"]["Requests"],
            {"GPDMA1.GPDMACH0": "USART1_TX", "GPDMA1.GPDMACH1": "USART1_RX"},
        )
        code = self.generate(parsed, use_xrobot=False)
        self.assertIn("usart1_rx_buf, usart1_tx_buf, 5);", code)
        self.assertIn("alignas(4) static uint8_t usart1_tx_buf[128];", code)

    def test_hpdma_and_lpdma_requests_are_read_as_well(self):
        ioc = H5_IOC.replace("GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX", "").replace(
            "GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX",
            "HPDMA1.REQUEST_HPDMACH3=HPDMA1_REQUEST_USART1_TX\n"
            "LPDMA1.REQUEST_LPDMACH0=LPDMA1_REQUEST_USART1_RX",
        )
        usart1 = self.parse(ioc)["Peripherals"]["USART"]["USART1"]
        self.assertEqual(
            [(d["dma_type"], d["stream"]) for d in usart1["dma"].values()],
            [("HPDMA", "HPDMA1_Channel3"), ("LPDMA", "LPDMA1_Channel0")],
        )

    def test_linked_list_requests_are_warned_about(self):
        # 链表模式的请求在 Linkedlist.<通道>.<队列>.<节点>.Requestforcodegen 中，不读取。
        # Linked-list requests are in Linkedlist.<channel>.<queue>.<node>.Requestforcodegen
        # and are not read.
        ioc = H5_IOC.replace(
            "GPDMA1.REQUEST_GPDMACH0=GPDMA1_REQUEST_USART1_TX\n"
            "GPDMA1.REQUEST_GPDMACH1=GPDMA1_REQUEST_USART1_RX\n",
            "Linkedlist.MDMA_Channel0.GP_SW.0.Requestforcodegen=GPDMA1_REQUEST_USART1_TX\n"
            "Linkedlist.MDMA_Channel0.GP_SW.1.Requestforcodegen=GPDMA1_REQUEST_USART1_TX\n"
            "Linkedlist.MDMA_Channel1.GP_SW.0.Requestforcodegen=GPDMA1_REQUEST_USART1_RX\n",
        )
        usart1 = self.parse(ioc)["Peripherals"]["USART"]["USART1"]
        self.assertNotIn("DMA_TX", usart1)
        self.assertIn(
            "WARNING:root:DMA requests in linked-list mode are not read: USART1_RX, USART1_TX; "
            "these peripherals get no DMA buffers",
            self.logs.output,
        )
        self.assertIn("{nullptr, 0}, {nullptr, 0}, 5);", self.generate(self.parse(ioc), False))

    def test_simple_requests_give_no_linked_list_warning(self):
        self.parse(H5_IOC)
        self.assertEqual([line for line in self.logs.output if "linked-list" in line], [])


class HandleModes(TestCase):
    """模式决定 CubeMX 生成哪种 HAL 句柄；没有 LibXR 所需句柄的实例不生成。
    The mode decides which HAL handle CubeMX generates; an instance without the handle LibXR
    needs is not generated.
    """

    parse = ParsedConfiguration.parse

    def test_a_synchronous_usart_is_not_generated(self):
        # 以前照样生成 STM32UART usart1(&huart1, …)，工程里没有 huart1，链接失败。
        # STM32UART usart1(&huart1, ...) used to be generated; the project has no huart1 and
        # fails to link.
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("", SYNC_USART_IOC)["Peripherals"]
        self.assertNotIn("USART", peripherals)
        self.assertIn(
            "WARNING:root:USART1 is not generated: Synchronous Slave mode uses "
            "USART_HandleTypeDef, and LibXR's STM32UART needs a UART handle",
            logs.output,
        )

    def test_a_smbus_i2c_is_not_generated(self):
        with self.assertLogs(level="WARNING") as logs:
            peripherals = self.parse("", SMBUS_IOC)["Peripherals"]
        self.assertNotIn("I2C", peripherals)
        self.assertIn(
            "WARNING:root:I2C2 is not generated: SMBus mode uses SMBUS_HandleTypeDef, and "
            "LibXR's STM32I2C needs an I2C handle",
            logs.output,
        )

    def test_asynchronous_uarts_keep_their_mode(self):
        with self.assertLogs(level="WARNING"):
            h5 = self.parse("", H5_IOC)["Peripherals"]["USART"]["USART1"]
        f4 = self.parse("")["Peripherals"]["USART"]
        self.assertEqual(
            [h5["Mode"], f4["USART1"]["Mode"], f4["USART6"]["Mode"]], ["Asynchronous"] * 3
        )


class Rtos(TestCase):
    """FreeRTOS 和 ThreadX 的不同来源都写出对应的段，libxr gen 据此选择 LibXR 的系统。
    Every source of FreeRTOS and ThreadX gives its section, from which libxr gen selects the
    LibXR system.
    """

    parse = ParsedConfiguration.parse

    def test_the_x_cube_freertos_pack_is_freertos(self):
        # 以前没有 FreeRTOS 段，libxr gen 按裸机生成。
        # There used to be no FreeRTOS section, and libxr gen generated for bare metal.
        with self.assertLogs(level="WARNING"):
            parsed = self.parse(
                "Mcu.ThirdParty0=STMicroelectronics.X-CUBE-FREERTOS.1.6.0\n"
                "STMicroelectronics.X-CUBE-FREERTOS.1.6.0.configTOTAL_HEAP_SIZE=4096\n",
                H5_IOC,
            )
        self.assertEqual(
            parsed["FreeRTOS"],
            {"RTOS": "FreeRTOS", "Enabled": True, "Tasks": {}, "Heap": "4096B", "Features": []},
        )

    def test_the_threadx_middleware_is_threadx(self):
        # 参数全为默认值时（如 STM32CubeH5 的 USBX 例程）.ioc 中只有 Mcu.IPn=THREADX。
        # With every parameter at its default, as in the USBX examples of STM32CubeH5, the
        # .ioc file only has Mcu.IPn=THREADX.
        for extra, pool in (
            ("THREADX.TX_APP_CREATION=1\nTHREADX.TX_APP_MEM_POOL_SIZE=3*1024\n", "3*1024B"),
            ("Mcu.IP9=THREADX\n", None),
        ):
            with self.subTest(extra=extra), self.assertLogs(level="WARNING"):
                parsed = self.parse(extra, H5_IOC)
                self.assertEqual(parsed["ThreadX"]["MemPoolSize"], pool)
                self.assertNotIn("FreeRTOS", parsed)

    def test_a_project_without_an_rtos_has_neither_section(self):
        parsed = self.parse("")
        self.assertNotIn("FreeRTOS", parsed)
        self.assertNotIn("ThreadX", parsed)


class Pins(TestCase):
    """引脚名 PxN 的端口字母从 A 到 Z。
    The port letter of a pin name PxN runs from A to Z.
    """

    parse = ParsedConfiguration.parse

    def test_stm32n6_ports_after_k_are_read(self):
        # CubeMX 的 STM32N6 引脚表有 PN0 等 PN～PQ 端口的引脚；以前只认 PA～PK，这些 GPIO 被丢掉。
        # The STM32N6 pin list of CubeMX has pins such as PN0 on ports PN to PQ; only PA to PK
        # used to be read, and these GPIOs were dropped.
        gpio = self.parse(
            "PN0.GPIO_Label=LED_N\nPN0.Signal=GPIO_Output\nPO1.GPIO_Label=KEY_O\nPO1.Signal=GPXTI1\n"
        )["GPIO"]
        self.assertEqual(
            {pin: gpio[pin] for pin in ("PN0", "PO1")},
            {
                "PN0": {"Label": "LED_N", "Signal": "GPIO_Output"},
                "PO1": {"Label": "KEY_O", "Signal": "GPXTI1", "GPXTI": True},
            },
        )


class RegularConversions(GeneratorTestCase):
    """ADC 规则通道按 rank 排列，DMA 模式下第 i 个通道引用读 DMA 缓冲区的第 i 格。
    ADC regular channels follow their ranks; in DMA mode channel reference i reads slot i of
    the DMA buffer.
    """

    def parse(self, ioc):
        """解析 ioc 并返回 ADC3 的配置；忽略 SysTick 时基的警告。
        Parse ioc and return the configuration of ADC3; the SysTick timebase warning is
        ignored.
        """
        with self.assertLogs(level="WARNING"):
            self.parsed = ParsedConfiguration.parse(self, "", ioc)
        return self.parsed["Peripherals"]["ADC"]["ADC3"]

    def test_ranks_follow_their_numbers_not_the_key_order(self):
        # 以前按 key 的文本顺序收集并去重，得到 IN8、1、15、2…14 共 11 个，第 3 个起都错位。
        # Channels used to be collected in key text order without repeats: IN8, 1, 15, 2 ... 14,
        # 11 of them, every one from the third on in the wrong slot.
        ranks = [8, 1, 2, 3, 5, 6, 7, 9, 13, 14, 15, 8]
        adc3 = self.parse(ADC_RANKS_IOC)
        self.assertEqual(adc3["RegularConversions"], [f"ADC_CHANNEL_{n}" for n in ranks])
        self.assertEqual(adc3["Channels"], [f"ADC_CHANNEL_{n}" for n in ranks[:-1]])

    def test_a_repeated_rank_gets_its_own_reference(self):
        self.parse(ADC_RANKS_IOC)
        code = self.generate(self.parsed, use_xrobot=False)
        self.assertIn("ADC_CHANNEL_14, ADC_CHANNEL_15, ADC_CHANNEL_8}, 3.3);", code)
        self.assertIn("static auto& adc3_adc_channel_8 = adc3.GetChannel(0);", code)
        self.assertIn("static auto& adc3_adc_channel_15 = adc3.GetChannel(10);", code)
        self.assertIn("static auto& adc3_adc_channel_8_rank12 = adc3.GetChannel(11);", code)
        self.assertIn("alignas(4) static uint16_t adc3_buf[192];", code)

    def test_any_number_of_ranks_keeps_the_rank_order(self):
        for count in range(1, 17):
            with self.subTest(count=count):
                channels = [f"ADC_CHANNEL_{(7 * i + 3) % 16}" for i in range(count)]
                lines = [
                    rf"ADC3.Channel-{i}\#ChannelRegularConversion={channel}"
                    for i, channel in enumerate(channels)
                ]
                # CubeMX 按去掉转义后的 key 排序保存。
                # CubeMX saves the keys sorted with the escapes removed.
                lines.sort(key=lambda line: line.split("=")[0].replace("\\", ""))
                adc3 = self.parse("\n".join(lines) + "\nDma.Request0=ADC3\n")
                self.assertEqual(adc3["RegularConversions"], channels)


class Timebase(TestCase):
    """HAL 时基应是中断优先级最高的普通定时器，否则警告。
    The HAL timebase should be a general-purpose timer with the highest interrupt priority;
    anything else is warned about.
    """

    TIMER = "NVIC.TimeBase=TIM6_DAC_IRQn\nNVIC.TimeBaseIP=TIM6\n"
    parse = ParsedConfiguration.parse

    def test_systick_is_warned_about(self):
        with self.assertLogs(level="WARNING") as logs:
            self.assertEqual(self.parse("")["Timebase"], {"Source": "SysTick", "IRQ": None})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase is SysTick. In STM32CubeMX, set SYS > Timebase "
                "Source to a general-purpose timer (such as TIM6) and give its interrupt the "
                "highest preemption priority (0) in NVIC."
            ],
        )

    def test_a_timer_needs_the_highest_priority(self):
        with self.assertLogs(level="WARNING") as logs:
            timebase = self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:5\\:0\\:false\\:true\n")
        self.assertEqual(timebase["Timebase"], {"Source": "TIM6", "IRQ": "TIM6_DAC_IRQn"})
        self.assertEqual(
            logs.output,
            [
                "WARNING:root:The HAL timebase interrupt TIM6_DAC_IRQn (TIM6) has preemption "
                "priority 5. In STM32CubeMX, set it to the highest (0) in NVIC."
            ],
        )
        with self.assertNoLogs(level="WARNING"):
            self.parse(self.TIMER + "NVIC.TIM6_DAC_IRQn=true\\:0\\:0\\:false\\:true\n")


if __name__ == "__main__":
    unittest.main()
