#!/usr/bin/env python
"""libxr stm32 cmake：把 LibXR 接入 CubeMX 生成的 CMake 工程。
libxr stm32 cmake: integrate LibXR into a CMake project generated by CubeMX.

生成或更新 cmake/LibXR.CMake，调整 ST Arm Clang 工具链文件，并在 CMakeLists.txt 中 include
LibXR.CMake。这些文件改变后，已有的构建目录在下次构建时由 CMake 重新配置。
It generates or updates cmake/LibXR.CMake, adjusts the ST Arm Clang toolchain file and
includes LibXR.CMake from CMakeLists.txt. CMake reconfigures existing build directories on
their next build after these files change.
"""

import logging
import os
import re
import sys
from pathlib import Path

from xr_syntax.cpp import CppDocument
from xr_syntax.i18n import tr

LIBXR_CMAKE_TEMPLATE = """set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# LibXR
set(LIBXR_SYSTEM _LIBXR_SYSTEM_)
set(LIBXR_DRIVER st)
_XROBOT_MODULES_DIR_add_subdirectory(Middlewares/Third_Party/LibXR)
target_link_libraries(xr
    PUBLIC stm32cubemx
)
target_compile_features(xr PUBLIC cxx_std_20)

set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED ON
)

target_include_directories(xr
    PUBLIC $<TARGET_PROPERTY:stm32cubemx,INTERFACE_INCLUDE_DIRECTORIES>
    PUBLIC Core/Inc
    PUBLIC User
)

# Add include paths
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
    # Add user defined include paths
    PUBLIC $<TARGET_PROPERTY:xr,INTERFACE_INCLUDE_DIRECTORIES>
    PUBLIC User
)

# Add linked libraries
target_link_libraries(${CMAKE_PROJECT_NAME}
    stm32cubemx

    # Add user defined libraries
    xr
)

file(
    GLOB LIBXR_USER_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/User/*.cpp")


target_sources(${CMAKE_PROJECT_NAME}
    PRIVATE ${LIBXR_USER_SOURCES}
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE -Og)
    target_compile_options(xr PRIVATE -O2)
    if(TARGET FreeRTOS)
        target_compile_options(FreeRTOS PRIVATE -O2)
    endif()

    if(TARGET STM32_Drivers)
        target_compile_options(STM32_Drivers PRIVATE -O2)
    endif()

    if(TARGET USB_Device_Library)
        target_compile_options(USB_Device_Library PRIVATE -O2)
    endif()
endif()
"""

XROBOT_MODULES_DIR_LINE = "set(XROBOT_MODULES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Modules)\n"

include_cmake_cmd = "include(${CMAKE_CURRENT_LIST_DIR}/cmake/LibXR.CMake)\n"

# 非注释行中任意写法的 include(...LibXR.CMake)。
# An include(...LibXR.CMake) in any spelling on a line that is not a comment.
_LIBXR_CMAKE_INCLUDE = re.compile(
    r"^[ \t]*include[ \t]*\([^)#\n]*LibXR\.CMake[^)\n]*\)", re.IGNORECASE | re.MULTILINE
)


def includes_libxr_cmake(content: str) -> bool:
    """CMakeLists.txt 的内容 content 是否已经 include LibXR.CMake。
    Whether content, the text of a CMakeLists.txt, already includes LibXR.CMake.

    include 的路径写法和大小写不限，最后一行没有换行也算；被注释掉的行不算。只比较整行文字时，
    这些写法会被再追加一次 include，LibXR 随之被 add_subdirectory 两次，CMake 配置失败。
    Any spelling of the path and any case count, also on a last line without a newline; a
    commented-out line does not. Comparing whole lines would append a second include for these
    spellings, and LibXR would then be added twice and fail the CMake configure.
    """
    return _LIBXR_CMAKE_INCLUDE.search(content) is not None


def project_uses_xrobot(input_directory: str) -> bool:
    """User/app_main.cpp 由 --xrobot 生成时为真；文件不存在时为假。
    True when User/app_main.cpp was generated with --xrobot; False when the file is missing.

    libxr stm32 setup 在接入 CMake 之前生成该文件。
    libxr stm32 setup generates that file before the CMake integration.
    """
    return uses_xrobot(os.path.join(input_directory, "User", "app_main.cpp"))


def uses_xrobot(app_main: str) -> bool:
    """源文件 app_main 由 libxr gen --xrobot 生成时为真；文件不存在时为假。
    True when the source file app_main was generated by libxr gen --xrobot; False when the
    file is missing.

    libxr gen --xrobot 在 User Code 区域之外 include xrobot_main.hpp。
    libxr gen --xrobot includes xrobot_main.hpp outside the User Code regions.
    """
    if not os.path.isfile(app_main):
        return False
    document = CppDocument.parse(read_text_with_fallback(app_main))
    regions = [region.body_span for region in document.user_regions()]
    for include in document.include_views():
        start = include.node.span.start
        if include.header == "xrobot_main.hpp" and not any(
            span.start <= start < span.end for span in regions
        ):
            return True
    return False


def _follow_xrobot_choice(content: str, use_xrobot: bool) -> str:
    """让已有 LibXR.CMake 中的 XROBOT_MODULES_DIR 与入口源文件的选择一致，返回新内容。
    Make XROBOT_MODULES_DIR in an existing LibXR.CMake agree with the choice of the entry
    source and return the new content.

    使用 XRobot 而没有这一设置时，在 add_subdirectory(Middlewares/Third_Party/LibXR) 之前插入
    XROBOT_MODULES_DIR_LINE；找不到这一行时记录警告，内容不变。不使用 XRobot 而有这一设置时删除它。
    每次改动都记录一条说明。
    With XRobot and no such setting, XROBOT_MODULES_DIR_LINE is inserted before
    add_subdirectory(Middlewares/Third_Party/LibXR); without that line a warning is logged and
    the content stays. Without XRobot, an existing setting is removed. Each change is logged.
    """
    setting = re.compile(r"^\s*set\s*\(\s*XROBOT_MODULES_DIR\b[^\n]*\n?", re.MULTILINE)
    line = XROBOT_MODULES_DIR_LINE.strip()
    if use_xrobot and not setting.search(content):
        anchor = re.compile(
            r"^([ \t]*)add_subdirectory\s*\(\s*Middlewares/Third_Party/LibXR\s*\)", re.MULTILINE
        )
        if not anchor.search(content):
            logging.warning(
                tr(
                    "User/app_main.cpp uses XRobot, but LibXR.CMake does not set "
                    f"XROBOT_MODULES_DIR; add {line} before "
                    "add_subdirectory(Middlewares/Third_Party/LibXR)",
                    "User/app_main.cpp 使用了 XRobot，但 LibXR.CMake 没有设置 "
                    "XROBOT_MODULES_DIR；请在 add_subdirectory(Middlewares/Third_Party/LibXR) "
                    f"之前添加 {line}",
                )
            )
            return content
        logging.info(
            tr(
                f"LibXR.CMake: added {line}, as User/app_main.cpp uses XRobot",
                f"LibXR.CMake：User/app_main.cpp 使用了 XRobot，已加入 {line}",
            )
        )
        return anchor.sub(lambda m: m.group(1) + line + "\n" + m.group(0), content, 1)
    if not use_xrobot and setting.search(content):
        logging.info(
            tr(
                "LibXR.CMake: removed XROBOT_MODULES_DIR, as User/app_main.cpp does not use XRobot",
                "LibXR.CMake：User/app_main.cpp 没有使用 XRobot，已删除 XROBOT_MODULES_DIR",
            )
        )
        return setting.sub("", content)
    return content


def normalize_libxr_cmake(content: str, system: str) -> str:
    """把已有 LibXR.CMake 的内容调整为 C++20 和给定的 LIBXR_SYSTEM，返回新内容。
    Adjust the content of an existing LibXR.CMake to C++20 and the given LIBXR_SYSTEM and
    return the new content.

    CMAKE_CXX_STANDARD 与 CMAKE_CXX_STANDARD_REQUIRED 的设置移到开头并设为 20 和 ON；LIBXR_SYSTEM
    的值被替换，没有这一行时插在 LIBXR_DRIVER 行之前；xr 的 cxx_std 编译特性改为 20，没有时补在
    target_link_libraries(xr ...) 之后；缺少工程目标的 CXX_STANDARD 属性时插在
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE 之前；收集 User/*.cpp 的 GLOB 加上
    CONFIGURE_DEPENDS，新加入的源文件在下次构建时被编译。
    The CMAKE_CXX_STANDARD and CMAKE_CXX_STANDARD_REQUIRED settings move to the top as 20 and
    ON; the LIBXR_SYSTEM value is replaced, or the line is inserted before the LIBXR_DRIVER
    line; the cxx_std compile feature of xr becomes 20, or is added after
    target_link_libraries(xr ...); missing CXX_STANDARD properties of the project target are
    inserted before target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE; the GLOB of
    User/*.cpp gets CONFIGURE_DEPENDS, so a new source file is compiled on the next build.
    """
    content = re.sub(
        r"^\s*set\s*\(\s*CMAKE_CXX_STANDARD\s+\d+\s*\)\s*\n?", "", content, flags=re.MULTILINE
    )
    content = re.sub(
        r"^\s*set\s*\(\s*CMAKE_CXX_STANDARD_REQUIRED\s+\S+\s*\)\s*\n?",
        "",
        content,
        flags=re.MULTILINE,
    )
    content = (
        "set(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n" + content.lstrip("\n")
    )

    system_pattern = re.compile(r"(^\s*set\s*\(\s*LIBXR_SYSTEM\s+)(\S+)(\s*\)\s*)", re.MULTILINE)
    if system_pattern.search(content):
        content = system_pattern.sub(rf"\1{system}\3", content, count=1)
    else:
        content = re.sub(
            r"(^\s*set\s*\(\s*LIBXR_DRIVER\s+\S+\s*\)\s*$)",
            f"set(LIBXR_SYSTEM {system})\n\\1",
            content,
            count=1,
            flags=re.MULTILINE,
        )

    content = re.sub(
        r"target_compile_features\s*\(\s*xr\s+PUBLIC\s+cxx_std_\d+\s*\)",
        "target_compile_features(xr PUBLIC cxx_std_20)",
        content,
        count=1,
    )
    if "target_compile_features(xr PUBLIC cxx_std_20)" not in content:
        content = re.sub(
            r"(target_link_libraries\s*\(\s*xr\b[\s\S]*?\)\s*)",
            r"\1\ntarget_compile_features(xr PUBLIC cxx_std_20)\n",
            content,
            count=1,
        )

    if "set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES" not in content:
        content = re.sub(
            r"(^\s*target_include_directories\(\$\{CMAKE_PROJECT_NAME\}\s+PRIVATE\s*$)",
            "set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES\n"
            "    CXX_STANDARD 20\n"
            "    CXX_STANDARD_REQUIRED ON\n"
            ")\n\n"
            r"\1",
            content,
            count=1,
            flags=re.MULTILINE,
        )

    content = re.sub(
        r"(\bGLOB\s+LIBXR_USER_SOURCES)(?!\s+CONFIGURE_DEPENDS\b)",
        r"\1 CONFIGURE_DEPENDS",
        content,
        count=1,
    )

    return content


def update_or_create_libxr_cmake(file_path: str, system: str, use_xrobot: bool) -> None:
    """更新已有的 LibXR.CMake，或按模板新建它。
    Update an existing LibXR.CMake, or create it from the template.

    已有文件经 normalize_libxr_cmake() 和 _follow_xrobot_choice() 调整，内容变化时才写回。新文件
    只在 use_xrobot 为真时设置 XROBOT_MODULES_DIR。
    An existing file is adjusted by normalize_libxr_cmake() and _follow_xrobot_choice() and
    written back only when it changes. A new file sets XROBOT_MODULES_DIR only when use_xrobot
    is true.
    """
    cmake_path = Path(file_path)

    if cmake_path.exists():
        content = read_text_with_fallback(str(cmake_path))
        new_content = _follow_xrobot_choice(normalize_libxr_cmake(content, system), use_xrobot)
        if new_content != content:
            cmake_path.write_text(new_content, encoding="utf-8", newline="\n")
            logging.info(
                tr(
                    f"Updated existing LibXR.CMake for system: {system}",
                    f"已按系统 {system} 更新现有的 LibXR.CMake",
                )
            )
        else:
            logging.info(
                tr(
                    "LibXR.CMake already up to date, no changes needed.",
                    "LibXR.CMake 已是最新，无需修改。",
                )
            )
    else:
        # XRobot 工程通过 LibXR 构建其 Modules；纯 LibXR 工程不得指定 Modules 目录。
        # XRobot projects build their Modules through LibXR; plain LibXR
        # projects must not name a Modules directory.
        cmake_path.write_text(
            LIBXR_CMAKE_TEMPLATE.replace("_LIBXR_SYSTEM_", system).replace(
                "_XROBOT_MODULES_DIR_", XROBOT_MODULES_DIR_LINE if use_xrobot else ""
            ),
            encoding="utf-8",
            newline="\n",
        )
        logging.info(
            tr(f"Generated LibXR.CMake at: {cmake_path}", f"已生成 LibXR.CMake：{cmake_path}")
        )


# 插在 CubeMX 的 set(STARM_TOOLCHAIN_CONFIG "<default>") 行之后；该行仍是唯一写出
# 默认配置的地方。
# Inserted after CubeMX's set(STARM_TOOLCHAIN_CONFIG "<default>") line, which
# stays the only place that names the default profile.
STARM_PROFILE_SELECTION = """
# LibXR: -DSTARM_TOOLCHAIN_CONFIG=<profile> selects the profile of a build
# directory; a default changed by libxr stm32 toolchain also reaches
# existing build directories.
set(_xr_starm_default ${STARM_TOOLCHAIN_CONFIG})
unset(STARM_TOOLCHAIN_CONFIG)
if(NOT DEFINED CACHE{STARM_TOOLCHAIN_CONFIG} OR
   (DEFINED CACHE{XR_STARM_TOOLCHAIN_DEFAULT} AND
    NOT XR_STARM_TOOLCHAIN_DEFAULT STREQUAL _xr_starm_default))
  set(STARM_TOOLCHAIN_CONFIG ${_xr_starm_default} CACHE STRING "ST Arm Clang runtime profile" FORCE)
endif()
set(XR_STARM_TOOLCHAIN_DEFAULT ${_xr_starm_default} CACHE INTERNAL "Default STARM_TOOLCHAIN_CONFIG of this file")
set_property(CACHE STARM_TOOLCHAIN_CONFIG PROPERTY STRINGS STARM_HYBRID STARM_NEWLIB STARM_PICOLIBC)"""


def normalize_starm_clang_toolchain(file_path: str | Path) -> None:
    """使 CubeMX 的 ST Arm Clang 运行时配置可按构建目录选择；文件不存在时不做任何事。
    Make CubeMX's ST Arm Clang runtime profile selectable per build directory; a missing file
    is left alone.

    libxr stm32 toolchain 通过改写本文件中的 set(STARM_TOOLCHAIN_CONFIG "...") 选择默认配置，
    构建时也可用 -DSTARM_TOOLCHAIN_CONFIG=... 选择其他配置。旧版本把默认行本身改成 CACHE STRING：
    缓存项只在构建目录第一次 configure 时初始化，因此切换到不了已有的构建目录。现在默认值保持为普通
    的一行；插入的选择块把配置保存在缓存中，文件中的默认值与上次 configure 记录的不同时替换它
    （每次 configure 都会重新读取工具链文件）。
    libxr stm32 toolchain selects the default profile by rewriting
    set(STARM_TOOLCHAIN_CONFIG "...") in this file, and a build may select
    another one with -DSTARM_TOOLCHAIN_CONFIG=... . Earlier versions turned
    the default line itself into a CACHE STRING: a cache entry is only
    initialized by the first configure of a build directory, so the switch
    never reached an existing build tree. The default stays a plain line; the
    inserted selection block keeps the profile in the cache and replaces it
    when the file default differs from the one recorded at the last
    configure (the toolchain file is re-read on every configure).

    此外，CubeMX 计算 multilib 参数的 if/elseif 块之前会显式初始化 TOOLCHAIN_MULTILIBS，块中加入
    对未知配置名的 FATAL_ERROR。找不到 STARM_TOOLCHAIN_CONFIG 行时只记录警告；文件只在内容变化时
    以 LF 换行写回。
    In addition, TOOLCHAIN_MULTILIBS is initialized before the if/elseif block in which CubeMX
    computes the multilib flags, and that block gets a FATAL_ERROR for an unknown profile name.
    Without a STARM_TOOLCHAIN_CONFIG line only a warning is logged; the file is written back
    with LF line endings only when its content changes.
    """
    path = Path(file_path)
    if not path.exists():
        return

    content = read_text_with_fallback(str(path))
    line_pattern = re.compile(
        r'^(\s*set\s*\(\s*STARM_TOOLCHAIN_CONFIG\s+")([^"]+)'
        r'"(?:\s+CACHE\s+STRING\s+"[^"]*")?\s*\)[ \t]*$'
        # 旧版本在 CACHE 默认值之后写出的属性列表。
        # Property list written by earlier versions after a CACHE default.
        r"(?:\nset_property\s*\(\s*CACHE\s+STARM_TOOLCHAIN_CONFIG\s+PROPERTY\s+STRINGS"
        r"\s+STARM_HYBRID\s+STARM_NEWLIB\s+STARM_PICOLIBC\s*\))?",
        re.MULTILINE,
    )
    match = line_pattern.search(content)
    if match is None:
        logging.warning(
            tr(
                f"STARM_TOOLCHAIN_CONFIG not found in {path}",
                f"{path} 中没有 STARM_TOOLCHAIN_CONFIG",
            )
        )
        return

    replacement = f'{match.group(1)}{match.group(2)}")'
    if STARM_PROFILE_SELECTION not in content:
        replacement += STARM_PROFILE_SELECTION
    new_content = content[: match.start()] + replacement + content[match.end() :]

    # CubeMX 生成计算 multilib 参数的 if/elseif 块。显式初始化该变量，并拒绝拼错的运行时
    # 配置名。
    # CubeMX emits an if/elseif block that computes multilib flags. Initialize the
    # variable explicitly and reject misspelled runtime profiles.
    if 'set(TOOLCHAIN_MULTILIBS "")' not in new_content:
        marker = 'if(STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_HYBRID")'
        if marker in new_content:
            new_content = new_content.replace(marker, 'set(TOOLCHAIN_MULTILIBS "")\n\n' + marker, 1)

    first_if = new_content.find('if(STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_HYBRID")')
    if first_if >= 0:
        first_endif = new_content.find("endif()", first_if)
        if first_endif >= 0:
            block = new_content[first_if:first_endif]
            guard = (
                'elseif(NOT STARM_TOOLCHAIN_CONFIG STREQUAL "STARM_PICOLIBC")\n'
                '  message(FATAL_ERROR "Unknown STARM_TOOLCHAIN_CONFIG: '
                '${STARM_TOOLCHAIN_CONFIG}")\n'
            )
            if "Unknown STARM_TOOLCHAIN_CONFIG" not in block:
                new_content = new_content[:first_endif] + guard + new_content[first_endif:]

    if new_content != content:
        # 以 LF 写出，生成结果与平台无关。
        # Write LF line endings so the result does not depend on the platform.
        with path.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(new_content)
        logging.info(
            tr(
                f"Normalized STARM_TOOLCHAIN_CONFIG in {path}",
                f"已规范化 {path} 中的 STARM_TOOLCHAIN_CONFIG",
            )
        )


def read_text_with_fallback(path: str) -> str:
    """依次尝试以 UTF-8、UTF-8-SIG 和 GB18030 解码读取文本文件，返回第一个成功的结果。
    Read a text file with the first of UTF-8, UTF-8-SIG and GB18030 that decodes it.

    Raises:
        UnicodeDecodeError: 三种编码都无法解码该文件。
            None of the three encodings decodes the file.
    """
    for enc in ("utf-8", "utf-8-sig", "gb18030"):
        try:
            return Path(path).read_text(encoding=enc)
        except UnicodeDecodeError:
            continue
    return Path(path).read_text(encoding="utf-8")


def integrate(input_directory: str) -> None:
    """把 LibXR 接入 input_directory 中的 CubeMX CMake 工程。
    Integrate LibXR into the CubeMX CMake project in input_directory.

    依次生成或更新 cmake/LibXR.CMake，调整 cmake/starm-clang.cmake，并在 CMakeLists.txt 没有
    include LibXR.CMake 时（见 includes_libxr_cmake()）追加一行。LIBXR_SYSTEM 由 Core/Inc 中的
    FreeRTOSConfig.h 或 app_threadx.h 决定，都没有时为 None。输入目录或 CMakeLists.txt 不存在时
    以状态 1 退出。
    In order, it generates or updates cmake/LibXR.CMake, adjusts
    cmake/starm-clang.cmake, and appends a line that includes LibXR.CMake to CMakeLists.txt
    when it does not include it yet (see includes_libxr_cmake()). LIBXR_SYSTEM follows FreeRTOSConfig.h or app_threadx.h in Core/Inc, and
    is None without either. A missing input directory or CMakeLists.txt exits with status 1.
    """

    if not os.path.isdir(input_directory):
        logging.error(
            tr(f"Directory does not exist: {input_directory}", f"目录不存在：{input_directory}")
        )
        sys.exit(1)
    main_cmake_path = os.path.join(input_directory, "CMakeLists.txt")
    # 先检查 CMakeLists.txt，再写文件。
    # Check CMakeLists.txt before writing anything.
    if not os.path.exists(main_cmake_path):
        logging.error(tr(f"{main_cmake_path} not found.", f"找不到 {main_cmake_path}。"))
        sys.exit(1)

    cmake_dir = os.path.join(input_directory, "cmake")
    os.makedirs(cmake_dir, exist_ok=True)

    file_path = os.path.join(cmake_dir, "LibXR.CMake")

    freertos_enable = os.path.exists(
        os.path.join(input_directory, "Core", "Inc", "FreeRTOSConfig.h")
    )
    threadx_enable = os.path.exists(os.path.join(input_directory, "Core", "Inc", "app_threadx.h"))

    if freertos_enable:
        system = "FreeRTOS"
    elif threadx_enable:
        system = "ThreadX"
    else:
        system = "None"

    update_or_create_libxr_cmake(file_path, system, project_uses_xrobot(input_directory))

    normalize_starm_clang_toolchain(os.path.join(cmake_dir, "starm-clang.cmake"))

    cmake_content = read_text_with_fallback(main_cmake_path)
    if not includes_libxr_cmake(cmake_content):
        with open(main_cmake_path, "a", encoding="utf-8", newline="\n") as f:
            f.write("\n# Add LibXR\n" + include_cmake_cmd)
        logging.info(
            tr(
                "LibXR.CMake included in CMakeLists.txt.",
                "已在 CMakeLists.txt 中 include LibXR.CMake。",
            )
        )
    else:
        logging.info(
            tr(
                "LibXR.CMake already included in CMakeLists.txt.",
                "CMakeLists.txt 已经 include LibXR.CMake。",
            )
        )


if __name__ == "__main__":
    from libxr.legacy import run

    raise SystemExit(run("xr_stm32_cmake"))
