"""把 xrobot-org/libxr 的 master 当前所在的提交写入 src/libxr/libxr_version.py，并打印这个提交。
Write the commit that master of xrobot-org/libxr is on into src/libxr/libxr_version.py and print
that commit.

libxr stm32 setup 以这个提交作为 LibXR 的默认提交；CI 的 libxr-version 任务用打印出的提交
测试同一个 LibXR。
libxr stm32 setup uses this commit as the default LibXR commit; the libxr-version job of the
CI tests the same LibXR with the printed commit.
"""

import subprocess
import sys
from pathlib import Path

LIBXR_URL = "https://github.com/xrobot-org/libxr.git"
VERSION_FILE = Path(__file__).resolve().parents[1] / "src" / "libxr" / "libxr_version.py"


def write_version(commit: str, path: Path) -> None:
    """把 commit 写成 path 处的 libxr_version.py：带中英 docstring，符合 ruff 格式。
    Write commit as the libxr_version.py at path, with Chinese and English docstrings and in
    ruff format.
    """
    path.write_text(
        '"""由 scripts/gen_libxr_version.py 生成：libxr stm32 setup 默认使用的 LibXR 提交。\n'
        "Generated by scripts/gen_libxr_version.py: the LibXR commit libxr stm32 setup uses by\n"
        'default.\n"""\n\n\n'
        "class LibXRInfo:\n"
        '    """生成时 xrobot-org/libxr 的 master 所在的提交。\n'
        '    The commit master of xrobot-org/libxr was on when this file was generated.\n    """\n\n'
        f'    COMMIT = "{commit}"\n',
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    """查询 master 所在的提交，写入 libxr_version.py，把提交打印到标准输出。
    Look up the commit master is on, write it into libxr_version.py and print it to stdout.
    """
    output = subprocess.run(
        ["git", "ls-remote", LIBXR_URL, "refs/heads/master"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    if not output:
        sys.exit(f"{LIBXR_URL} has no master branch")
    commit = output.split()[0]
    write_version(commit, VERSION_FILE)
    print(f"Wrote {commit} to {VERSION_FILE}", file=sys.stderr)
    print(commit)


if __name__ == "__main__":
    main()
