// Generated by `libxr gen`. Edit only between "User Code Begin" and
// "User Code End"; everything else is rewritten when the file is regenerated.
#include "app_main.h"

#include "cdc_uart.hpp"
#include "libxr.hpp"
#include "main.h"
#include "stm32_adc.hpp"
#include "stm32_can.hpp"
#include "stm32_canfd.hpp"
#include "stm32_dac.hpp"
#include "stm32_flash.hpp"
#include "stm32_gpio.hpp"
#include "stm32_i2c.hpp"
#include "stm32_power.hpp"
#include "stm32_pwm.hpp"
#include "stm32_spi.hpp"
#include "stm32_timebase.hpp"
#include "stm32_uart.hpp"
#include "stm32_usb_dev.hpp"
#include "stm32_watchdog.hpp"
#include "flash_map.hpp"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */
// NOLINTBEGIN
// clang-format off
/* External HAL Declarations */
extern ADC_HandleTypeDef hadc1;
extern ADC_HandleTypeDef hadc3;
extern CAN_HandleTypeDef hcan2;
extern IWDG_HandleTypeDef hiwdg;
extern PCD_HandleTypeDef hpcd_USB_OTG_FS;
extern SPI_HandleTypeDef hspi1;
extern TIM_HandleTypeDef htim13;
extern TIM_HandleTypeDef htim1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart3;

/* DMA Resources */
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
#if defined(__SCB_DCACHE_LINE_SIZE)
#define XR_DCACHE_LINE_SIZE __SCB_DCACHE_LINE_SIZE
#else
#define XR_DCACHE_LINE_SIZE 32U
#endif
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint16_t data[32];
} adc1_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& adc1_buf = adc1_buf_storage.data;
#else
alignas(4) static uint16_t adc1_buf[32] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint16_t data[16];
} adc3_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& adc3_buf = adc3_buf_storage.data;
#else
alignas(4) static uint16_t adc3_buf[16] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[32];
} spi1_tx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& spi1_tx_buf = spi1_tx_buf_storage.data;
#else
alignas(4) static uint8_t spi1_tx_buf[32] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[32];
} spi1_rx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& spi1_rx_buf = spi1_rx_buf_storage.data;
#else
alignas(4) static uint8_t spi1_rx_buf[32] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[128];
} usart2_tx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& usart2_tx_buf = usart2_tx_buf_storage.data;
#else
alignas(4) static uint8_t usart2_tx_buf[128] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[128];
} usart2_rx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& usart2_rx_buf = usart2_rx_buf_storage.data;
#else
alignas(4) static uint8_t usart2_rx_buf[128] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[128];
} usart3_tx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& usart3_tx_buf = usart3_tx_buf_storage.data;
#else
alignas(4) static uint8_t usart3_tx_buf[128] __attribute__((section(".dma_buffer")));
#endif
#if defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
static struct alignas(XR_DCACHE_LINE_SIZE)
{
  uint8_t data[128];
} usart3_rx_buf_storage __attribute__((section(".dma_buffer")));
static constexpr auto& usart3_rx_buf = usart3_rx_buf_storage.data;
#else
alignas(4) static uint8_t usart3_rx_buf[128] __attribute__((section(".dma_buffer")));
#endif

extern "C" void app_main(void) {
  // clang-format on
  // NOLINTEND
  /* User Code Begin 2 */
  /* User Code End 2 */
  // clang-format off
  // NOLINTBEGIN
  static STM32TimerTimebase timebase(&htim13);
  PlatformInit(2, 1024);
  static STM32PowerManager power_manager;

  /* GPIO Configuration */
  static STM32GPIO IMU_INT(IMU_INT_GPIO_Port, IMU_INT_Pin, EXTI1_IRQn);
  static STM32GPIO IMU_CS(IMU_CS_GPIO_Port, IMU_CS_Pin);
  static STM32GPIO KEY2(KEY2_GPIO_Port, KEY2_Pin, EXTI15_10_IRQn);
  static STM32GPIO DXL_DIR(DXL_DIR_GPIO_Port, DXL_DIR_Pin);
  static STM32GPIO LED3(LED3_GPIO_Port, LED3_Pin);
  static STM32GPIO LED2(LED2_GPIO_Port, LED2_Pin);
  static STM32GPIO SW2(SW2_GPIO_Port, SW2_Pin);
  static STM32GPIO BUZZER_SIG(BUZZER_SIG_GPIO_Port, BUZZER_SIG_Pin);
  static STM32GPIO DXL_PWR_EN(DXL_PWR_EN_GPIO_Port, DXL_PWR_EN_Pin);
  static STM32GPIO LED4(LED4_GPIO_Port, LED4_Pin);
  static STM32GPIO SW1(SW1_GPIO_Port, SW1_Pin);
  static STM32GPIO LED1(LED1_GPIO_Port, LED1_Pin);
  static STM32GPIO KEY1(KEY1_GPIO_Port, KEY1_Pin, EXTI3_IRQn);
  static STM32GPIO LED_RUN(LED_RUN_GPIO_Port, LED_RUN_Pin);

  static STM32ADC adc1(&hadc1, adc1_buf, {ADC_CHANNEL_VREFINT, ADC_CHANNEL_VBAT}, 3.3);
  static auto& adc1_adc_channel_vrefint = adc1.GetChannel(0);
  UNUSED(adc1_adc_channel_vrefint);
  static auto& adc1_adc_channel_vbat = adc1.GetChannel(1);
  UNUSED(adc1_adc_channel_vbat);

  static STM32ADC adc3(&hadc3, adc3_buf, {ADC_CHANNEL_10}, 3.3);
  static auto& adc3_adc_channel_10 = adc3.GetChannel(0);
  UNUSED(adc3_adc_channel_10);


  static STM32SPI spi1(&hspi1, spi1_rx_buf, spi1_tx_buf, 3);

  static STM32UART usart2(&huart2,
              usart2_rx_buf, usart2_tx_buf, 5);

  static STM32UART usart3(&huart3,
              usart3_rx_buf, usart3_tx_buf, 5);

  static STM32CAN can2(&hcan2, 5);

  static STM32Watchdog iwdg(&hiwdg, 5000, 250);

  /* Terminal Configuration */

  iwdg.Feed();
  static auto iwdg_task = Timer::CreateTask(iwdg.TaskFun, reinterpret_cast<LibXR::Watchdog *>(&iwdg), 250);
  Timer::Add(iwdg_task);
  Timer::Start(iwdg_task);

  XR_REGISTER(power_manager, LibXR::PowerManager);
  XR_REGISTER(IMU_INT, LibXR::GPIO);
  XR_REGISTER(IMU_CS, LibXR::GPIO);
  XR_REGISTER(KEY2, LibXR::GPIO);
  XR_REGISTER(DXL_DIR, LibXR::GPIO);
  XR_REGISTER(LED3, LibXR::GPIO);
  XR_REGISTER(LED2, LibXR::GPIO);
  XR_REGISTER(SW2, LibXR::GPIO);
  XR_REGISTER(BUZZER_SIG, LibXR::GPIO);
  XR_REGISTER(DXL_PWR_EN, LibXR::GPIO);
  XR_REGISTER(LED4, LibXR::GPIO);
  XR_REGISTER(SW1, LibXR::GPIO);
  XR_REGISTER(LED1, LibXR::GPIO);
  XR_REGISTER(KEY1, LibXR::GPIO);
  XR_REGISTER(LED_RUN, LibXR::GPIO);
  XR_REGISTER(adc1_adc_channel_vrefint, LibXR::ADC);
  XR_REGISTER(adc1_adc_channel_vbat, LibXR::ADC);
  XR_REGISTER(adc3_adc_channel_10, LibXR::ADC);
  XR_REGISTER(spi1, LibXR::SPI);
  XR_REGISTER(usart2, LibXR::UART);
  XR_REGISTER(usart3, LibXR::UART);
  XR_REGISTER(can2, LibXR::CAN);
  XR_REGISTER(iwdg, LibXR::Watchdog);

  // clang-format on
  // NOLINTEND
  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}